### ISSUE TITLE
Tag template function to support standard CSS syntax?

### ISSUE THREAD

**Issue by hadfieldn** [styletron/styletron#110]
I came across Styletron by reading https://dev.to/kayis/styletron-react-component-styles-on-steroids. Great idea, seems like a natural extension of React.

I'm wondering if you've considered making a tag template function that would allow the same syntax that [styled-components](https://github.com/styled-components/styled-components) uses? One of the things I like about styled-components is that it lets me use my IDE's support for CSS (IntelliJ). Also, having this would make it much easier to transition existing code from styled-components to Styletron.

Is this something you've considered and perhaps dismissed for technical reasons, or is it more just a matter of not having been a top priority? Thanks!

**Comment by ludovicofischer** [comment]
Styletron and Styletron React are separate, so there should be no need to change Styletron itself for this. You could implement something like the styled components API as a separate library that uses Styletron, just like the current React bindings.

 Also look at Fela, it has the same style deduplication as Styletron and a similar architecture, so maybe someone has already implemented it there.

**Comment by jbellsey** [comment]
You can look at the [css-to-js](https://github.com/jakecoxon/babel-plugin-css-to-js) Babel plugin:

```js
const styles = css`
  font-size: 20px
`;
```

Not sure how to get IntelliJ to lint or code-complete inside a template literal. Seems like this is a problem [for](https://github.com/styled-components/styled-components/issues/637) [styled](https://github.com/styled-components/styled-components/issues/176)-[components](https://youtrack.jetbrains.com/issue/WEB-24148) as well.

**Comment by rtsao** [comment]
The current incarnation of Styletron is opinionated toward style objects so I think first-class support for this is this probably out of scope.

**Comment by leyanlo** [comment]
@rtsao Would it be possible to revisit this idea? I’m finding working with Styletron to be painful, since CSS is ordered whereas JS objects are not. It is difficult to audit instances of mixing shorthand and longhand properties, especially when building reusable components for others to consume. E.g. when building a component library, updating a style from shorthand to longhand can be a breaking change, depending on how consumers restyle a component.

Normally, when building CSS you can override styles by appending the updated rules, but that is not always deterministic with Styletron. Styletron is even self-aware and includes a Pitfalls section https://www.styletron.org/concepts/#pitfalls

Maybe instead of having this pitfall, we could reach a happy medium using the tagged template literal syntax but spit out atomic rules? E.g.
```js
const Content = styled.div`
  border: 2px solid black;
`;
const CustomContent = styled(Content)`
  border-width: 5px;
`;
```
would be valid, and compile to
```css
.ae { border: 2px solid black; }
.af { border: 5px solid black; }
```
This would never throw a warning, since it is always clear what to do given how CSS works.
