### ISSUE TITLE
Wrong order of media style tags

### ISSUE THREAD

**Issue by andreiduca** [styletron/styletron#113]
The order of the media style tags should be considered. In a mobile-first approach, this breaks the layout: rules defined for smaller screens are placed after rules defined for bigger screens and will always take precedence.

<img width="600" alt="screenshot 2017-04-11 16 29 20" src="https://cloud.githubusercontent.com/assets/2589135/24914274/0dac7c2a-1ed4-11e7-83fa-b91e5713d2dc.png">

**Comment by rtsao** [comment]
Yeah, this can be a problem if any conflicting declarations are used on the same element. I think this is especially a problem with media queries because with Styletron you don't have control over media query order.

My preference in solving this is to simply use disjoint (i.e. non-overlapping) media queries on the same element so a conflict will never occur. Helper functions can keep things DRY.

The alternative solution would be to sort the media queries in some deterministic fashion. I don't love this idea for a couple reasons:
- We can't know for sure the "correct" way to sort media queries. An arbitrary, deterministic algorithm could be chosen, but I don't like the idea of making an assumption. Normally with CSS, the user always manually specifies media query order in the stylesheet (with the lattermost always taking priority), but we have no equivalent for declarative priority in atomic CSS.
- The logic for sorting media queries would need to be shipped to the client. This is going to be a kilobyte or two, which in my opinion is not strictly necessary.

**Comment by deamme** [comment]
I'm also doing mobile-first approach and I think a lot of people do.. Right now the media queries does not work for me at all. A quick fix would just be ordering min-width px values from low to high.

**Comment by andreiduca** [comment]
The order of the media queries is determined by the order of the components in the React tree, for example.

So if I have component A that only has styles for higher media queries, and then component B that has styles for both small and big media queries, the styles tags will be inserted in the order they appear: higher media queries first, then lower ones. So component B will always get the lower resolution styles, because at 1400px both 'min-width: 1024px' and 'min-width: 400px' are true. 

Ex: if B has 'color: red' for lower media queries and 'color: blue' for higher media queries, because of the order the media queries are inserted in the header from components A and B respectively, B will always be red.

**Comment by sammkj** [comment]
I got hit hard on this as well.

@rtsao what do you mean by disjoint media queries? Can you elaborate on that?

**Comment by rtsao** [comment]
I would do something akin to this, based on the [Bootstrap responsive breakpoints](https://v4-alpha.getbootstrap.com/layout/responsive-utilities/):

```js
const xs = '@media (max-width: 543px)';
const sm = '@media (min-width: 544px) and (max-width: 767px)';
const md = '@media (min-width: 768px) and (max-width: 991px)';
const lg = '@media (min-width: 992px) and (max-width: 1199px)';
const xl = '@media (min-width: 1200px)';

function media(query, style) {
  const viewports = {
    'xs-down': [xs],
    'sm-down': [xs, sm],
    'md-down': [xs, sm, md],
    'lg-down': [xs, sm, md, lg],
    'xl-down': [xs, sm, md, lg, xl],
    'xs-up': [xs, sm, md, lg, xl],
    'sm-up': [sm, md, lg, xl],
    'md-up': [md, lg, xl],
    'lg-up': [lg, xl],
    'xl-up': [xl]
  }[query];

  if (viewports) {
    return multi(viewports, style);
  }
}

// duplicate value for multiple keys
const multi = (keys, style) =>
  Object.assign.apply(null, keys.map(key => ({[key]: style})));

// shallow merge values one level deep
const mergeShallow = (styles) =>
  styles.reduce((acc, style) => {
    for (let prop in style) {
      const val = style[prop];
      if (typeof val === 'object') {
        acc[prop] = acc[prop] || {};
        for (let inner in val) {
          acc[prop][inner] = val[inner];
        }
      } else {
        acc[prop] = val;
      }
    }
    return acc;
  }, {});

const myStyle = {
  ...mergeShallow([
    media('xs-up', {
      color: 'red',
      fontSize: '10px'
    }),
    media('md-up', {
      color: 'blue',
      fontSize: '20px'
    }),
  ]),
  color: 'green'
};

/*
{
  "@media (max-width: 543px)": {
    "color": "red",
    "fontSize": "10px"
  },
  "@media (min-width: 544px) and (max-width: 767px)": {
    "color": "red",
    "fontSize": "10px"
  },
  "@media (min-width: 768px) and (max-width: 991px)": {
    "color": "blue",
    "fontSize": "20px"
  },
  "@media (min-width: 992px) and (max-width: 1199px)": {
    "color": "blue",
    "fontSize": "20px"
  },
  "@media (min-width: 1200px)": {
    "color": "blue",
    "fontSize": "20px"
  },
  "color": "green"
}
*/
```
There's no need to worry about non-determinism relating to media queries because none of them overlap. You can build utilities on top that make it seem like you have larger, more broad media queries, but since under the hood they don't overlap, you're in the clear. So however you end up merging these media queries, it will produce a final style object that will have deterministic precedence.

**Comment by sammkj** [comment]
Thank you for the detailed response! At first glance, it seems a bit constrained because I can only declare a set amount of breakpoints. But I will experiment and see how it goes!

**Comment by rtsao** [comment]
You can actually have arbitrary media queries, it's just the key thing is you don't use overlapping media queries on the same element with conflicting declarations. So you're free to use overlapping media queries, but not on the same element in the case where the overlapping media queries have conflicting declarations (i.e. two different `color` declarations).

**Comment by andreiduca** [comment]
I get your point, but this gets out of proportion and is not exactly the desired outcome. Plus, you get duplicated declarations all over. Compare your outcome with the following, which is the more clean, mobile-first code:

```js
{
  "color": "green"
  "@media (min-width: 544px)": {
    "color": "red"
  },
  "@media (min-width: 992px)": {
    "color": "blue",
    "fontSize": "20px"
  },
}
```

**Comment by rtsao** [comment]
Agreed it isn't as nice. I suspect in practice the extra declarations wouldn't make much of a difference depending on how heavily media queries are used and how many different viewports you care about. But I'm definitely open to more ideas on how a better solution could be achieved.

Two possible ideas I have:

1. There will probably be [some middleware/plugin interface](https://github.com/rtsao/styletron/pull/91) in the future. I think sorting of styles (such as media queries, shorthands, and pseudo selectors) would be a good candidate for this. It's definitely something to keep in mind when figuring out how these plugins will work and what the interface for plugins will be.

2. What if there was an interface for providing up-front an ordered list of media queries. The output order of any styles using these media queries would be then guaranteed. I think this wouldn't be too difficult to implement.

**Comment by andreiduca** [comment]
Well, option 2. is what I'm currently doing. So one can make sure that the top component will always have styles for ALL media queries, so they get generated in the correct order. Or have like an `init()` method at the top of the js file that just generates empty or bogus styles for each media query, to ensure they are firstly inserted in the right order in the header. Anything after that gets injected in the appropriate `style` tag so everything is dandy.

Option 1. would be a nice opt-in method of making this work. I would however be curious how much complicated or costly would be for this to be part of the core. I think I'll give it a try some time in a near future.

**Comment by tajo** [comment]
solved with https://github.com/styletron/styletron/pull/296
