### ISSUE TITLE
"progressive" CSS

### ISSUE THREAD

**Issue by jakearchibald** [styletron/styletron#137]
I'm just reading up on the project, so apologies if this is already covered somewhere, or is otherwise stupid.

In terms of server rendering, is it possible to output a `<style>` just before each component, containing the additional not-already-output classes for that component?

I'm wondering if that would improve perceived performance, as rendering would require less CSS.

**Comment by rtsao** [comment]
It's cool you bring this up!

I was interested in progressive rendering too so several months ago, I did some experiments with [Inferno.js](https://github.com/infernojs/inferno) (and it's [streaming server-rendering functionality](https://github.com/infernojs/inferno/blob/master/packages/inferno-server/src/renderToString.stream.ts)) in conjunction with Styletron. I had a proof of concept working, so what you are describing is totally possible, but I don't think there's currently a nice way to do it with the current public API and `styletron-react` primitives.

But yeah, I think Styletron is perfect for progressive rendering. Adding first-class support for this should be pretty straightforward. If I can locate my streaming Inferno/Styletron end-to-end example I'll throw it up on a repo somewhere.

**Comment by jakearchibald** [comment]
That's really cool! I guess this would be easy-ish to do in userland if styletron had an API for "give me all the classes & rules defined thus far", and a way to make hydration work across multiple `<style>`s, if it doesn't already.

**Comment by rtsao** [comment]
Yep, I've already changed it to use and hydrates off multiple `<style>`s. The initial impetus for this was simplified  hydration of styles with media queries (I can use the media HTML attribute instead of wrapping the styles in an `@media` query) but the icing on the cake was multiple stylesheets was necessary for supporting progressive render.

I'll look into implementing a stateful API for flushing out newly added styles, but I'm also open to suggestions here. I suspect a good API might be forthcoming with a real end-to-end example, so I'll try and fish out that demo I made.

**Comment by mbrevda** [comment]
I'm wondering if support for this feature could eventually lead to css code splitting (i.e. something like [this](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin))? Not only would styletron generate the smallest css overall, but it would also allow for just the most minute amount of style to be loaded.
