### ISSUE TITLE
[suggestion] ThemeProvider idea?

### ISSUE THREAD

**Issue by lucasmotta** [styletron/styletron#141]
So I've been playing around recently with Styletron, Fela and Styled-Components to see the pros and cons of all those solutions.

One of the things I was looking into it was the support for Theming, which is present in both Fela and Styled-Components, but not on Styletron. So my question is very straightforward, is that something you would consider on implement within the `styletron-react` package?

It should be very straightforward to implement it, then we can pass down as a prop:

```js
// Heading.js
const Heading = styled('div', ({ theme }) => ({
  fontFamily: theme.font.heading,
  fontSize: '64px',
  color: theme.color.brand,
}))

// App.js
const theme = {
  font: {
    body: 'Helvetica, sans-serif',
    heading: 'Georgia, serif',
  },
  color: {
    brand: '#ff0000'
  }
}
render((
  <ThemeProvider theme={theme}>
    <Heading />
  </ThemeProvider>
), document.body);
```

Of if we don't want to create another Provider, we could simply pass the theme to the `StyletronProvider` instead.

Let me know your thoughts!

**Comment by jbellsey** [comment]
I have a rich theming package for styletron that I'm *this close* to getting approval to open source. 

I don't think this functionality belongs inside StyletronProvider. It's a separate tool for a separate purpose. You really only need one ThemeProvider object in your app, so it's not a big deal to add it to your harness. In my own lib, you can render ThemeProvider components any time you want a secondary theme. (Such as a sidebar theme.)

**Comment by dimitropoulos** [comment]
@jbellsey I see you have docs up for https://jbellsey.gitbooks.io/styletron-themer/ but I can't find the repo anywhere.  My team and I are probably about 35% into my own implementation of exactly the same thing (before I found the gitbook of your library).  I would be more than happy to contribute to your repo if you stand it up somewhere!

**Comment by jbellsey** [comment]
Well damn! I didn't intend for the docs to be public yet, but that's great anyway. I'd love to have your help. Right now the main help I need is political... getting approval to open source this little library is taking longer than I had expected. I'll post again as soon as I get it out the door.

**Comment by dimitropoulos** [comment]
Do you have any real timeline for that (lol, I know I know: sometimes impossible to get)?  I'm hoping to have something up and running later this coming week.  I've been in your position before, for sure, but perhaps it would help if you already have people willing to contribute?  

I can say for sure that everyone here at https://github.com/benzinga is willing to contribute.  If nothing else, perhaps we can have a small agreement/NDA kinda thing that can be arranged if it has to stay private for now?  I'm just trying to save us from working on something that already has been worked on, you know, and if we can do that at the same time as contributing back to your project then it's a win-win.

---------

other question: how does your library handle changing the theme in-app and rerendering thereafter.  most implementations I've seen use a subscription service of some kind to accomplish this (since using `context` basically forces you to).  I didn't see anything in the docs about this, and it's our main use-case.

**Comment by jbellsey** [comment]
I appreciate your enthusiasm! We have a meeting on Wednesday, where I'll lay down the gauntlet and ask for specific objections. If I have approval (and I have high hopes!) I'll put it online ASAP.

As for dynamic re-rendering: it's currently not set up for that. However, it's marked as a TODO, and will take all of 3 lines of code and a few tests to get it running. That might be your first pull request :)

Hang tight... I hope you'll be able to use it!

**Comment by dimitropoulos** [comment]
awesome! sounds like a plan! We would definitely want to work on that.  This is something that I would say is a necessary thing for styletron (most all the other mature competitors have this in place already), so we would be thrilled to help it get off the ground.

**Comment by dimitropoulos** [comment]
@jbellsey any update?

**Comment by jbellsey** [comment]
We just went live:

https://github.com/lookout/styletron-themer/
https://www.npmjs.com/package/styletron-themer

**Comment by dimitropoulos** [comment]
!!!!!!!!!!! yayyyyyyyyy

**Comment by oliviertassinari** [comment]
I have lost track of the theme package. Where can I find it?

*Also, it would be great to link the documentation URL in the GitHub repository :)*.
