### ISSUE TITLE
Non-atomic rendering engine

### ISSUE THREAD

**Issue by rtsao** [styletron/styletron#220]
Atomic rendering comes with particular tradeoffs that might not be appropriate for certain use cases and applications.

For this, there should be a standard non-atomic rendering engine (implementing the standard engine interface, but with monolithic, hashed classes). Then styled components could be used across either engine.

**Comment by tajo** [comment]
I agree that there are different trade-offs but not sure if this is completely valid: "*styled components could be used across either engine*".

I could see cases where the same styled component would work in the monolithic engine but not in atomic. For example with monolithic, you could get away with mixing longhands and shorthands or you could directly reference hashed classNames.

One reason I saw why people asked for the monolithic engine was having a better dev experience. So we did it at my previous project and it was a disaster since some bugs made it straight to the  production while everything was working great in the dev mode. We can rather improve the dev experience through some extension.

Anyway, assuming we will not actively develop / document / use the monolithic engine in a near-term, I am closing this issue.

**Comment by omeid** [comment]
This is a deal breaker. The DX of atomic engine is horrendous and the production value of atomic engine is not convincing.

**Comment by koulmomo** [comment]
> the production value of atomic engine is not convincing.

I agree that the DX could be better but clearly there **IS** real value in an atomic css approach. 

So much so that facebook has recently chosen an atomic engine for their rewrite of facebook.com (see: https://developers.facebook.com/videos/2019/building-the-new-facebookcom-with-react-graphql-and-relay/ start at ~28:30).

Yahoo saw the benefits of atomic css/classes all the way back in 2013 (see: https://www.smashingmagazine.com/2013/10/challenging-css-best-practices-atomic-approach/).

AtomicCSS works really well in production (performance!) especially for mega-sites like facebook and/or yahoo where you have 100(0)s of engineers building features and components that need to be styled and interact with each other without increasing bloat OR causing unintended bugs.

Agree with @tajo that I would rather invest more time in improving the dev experience. At least unless/until someone comes up with a better solution than atomic css

**Comment by tajo** [comment]
There is a [debug mode](https://www.styletron.org/api/#browser-debug-mode) that uses source-maps so you can directly jump from the inspected element to the source code. It's enabled by default in Fusion, Next.js and Gatsby scaffolds. (better documentation [coming](https://github.com/styletron/styletron.org/pull/7))

Also, we are about to release a [Chrome extension](https://github.com/styletron/styletron/pull/305) for Styletron that groups the styles together and other things.

**Comment by omeid** [comment]
The extension looks very good! :+1:
