### ISSUE TITLE
Prop for direct style overrides?

### ISSUE THREAD

**Issue by rtsao** [styletron/styletron#221]
It might be nice to have a built-in prop for style overrides directly.

Maybe something like this
```js
const Foo = styled("div", {color: "red"});

// shallow merge?
<Foo $style={{color: "green"}} />;

// transform?
<Foo $style={(style, props) => ({color: "green"})} />;
```

I think what is something unclear is what happens with the value, (e.g. replacement vs shallow merge vs deep merge). The nice thing about the HOCs is they are explicit.

**Comment by streamich** [comment]
You could use something like `jsxstyle` pattern:

```jsx
const Foo = jsxstyle('div', {color: 'red'});

<Foo $color="green" />;
```

**Comment by jbellsey** [comment]
I've been using the `withTransform` utility, something like this:

```js
// smart replacement for `styled`:
export const smartStyled = (...args) => withTransform(styled(...args), (style, props) => {
  const {$style} = props;
  if ($style)
    return _.merge({}, style, $style);
  return style;
});
```

Now my `smartStyled` components accept a `$style` prop which is integrated into Styletron's class system, rather than being rendered to HTML as an inline style:

```js
const Foo = smartStyled('div', {color: 'red'});
<Foo $style={{marginTop: '10px'}} />    // <div class = 'a b' />
```

I don't know it this can be integrated intelligently into the core `styled` HoC, but it sure would be useful.

**Comment by vikfroberg** [comment]
We used this initially on a project and it turned out to be one of the biggest mistakes. 

It’s better to use props for custom look and wrap the component with another one for layout. 

I do howerver nowdays use this pattern for ”building block” components. But they are easily defined with the current api. 

https://github.com/rtsao/styletron/issues/72

**Comment by schnerd** [comment]
It would be great to have this API. Our use case is we are developing reusable components but we want to allow the customers of our reusable components to override styles if they'd like:

```js
// text-input.js
const StyledInput = styled('input', ({width}) => ({width}));
const TextInput = ({$style}) => <StyledInput $style={$style} $isError={...} />;

// app.js
<TextInput $style={
  ({isError}) => ({borderColor: isError ? 'red' : 'blue'})
}} />
```

The `smartStyled` example is clever, but I think in order to support style functions (that receive props), styletron might need to offer this functionality as a core feature.

> think what is something unclear is what happens with the value, (e.g. replacement vs shallow merge vs deep merge)

I think you almost always want deep merge, and that's probably most in-line with what people expect from css-land. If you're completely replacing styles, might as well just define a brand new styled component. I struggle to think of a good use case for shallow merge. My vote would be that this should do a deep merge by default.

**Comment by schnerd** [comment]
For what it's worth, our team found a temporary workaround below:

```js
const baseStyled = createStyled({wrapper, getInitialStyle, driver});

export default function styled(elemType, objOrFn) {
  const component = baseStyled(elemType, objOrFn);

  // Use withStyleDeep to support $style fn/obj override
  return withStyleDeep(component, props => {
    const {$style} = props;
    if (typeof $style === 'function') {
      return $style(props);
    }
    return $style;
  });
}
```

That said, would still be great to get some sort of native support for this.

**Comment by tajo** [comment]
I guess we are ok for now to keep this solution in the userland and we can first give a try to the [hooks based API](https://github.com/styletron/styletron/issues/284).

**Comment by tajo** [comment]
Actually, we want to implement this to simplify the `styled` in `baseui`. The hook API has a different purpose.
