### ISSUE TITLE
Descendant combinators proposal

### ISSUE THREAD

**Issue by rtsao** [styletron/styletron#229]
I've been thinking how to make a robust implementation of this because it's a fairly common use case.

The proposed idea has a few nice properties:
- Still no true CSS selectors/class names
- Clear precedence / style resolution (this is needed because the normal JS method of resolving styles doesn't translate into CSS land)
- No brittle assumptions about component hierarchy. The correct ancestor/descendant relationship is enforced via the render prop API. (excluding portals, I suppose)

**Example**

I'm not totally happy with the names of things (still working on it), but hopefully the overall idea makes sense:
```jsx
import {createAncestor, Descendant} from "styletron-react";

const Foo = styled("div", {color: "green"});

const HoverSource1 = createAncestor(":hover", {
  color: "red"
});

const HoverSource2 = createAncestor(":hover", {
  color: "purple"
});

<HoverSource1 $as="div">
  {target1 => (
    <HoverSource2>
      {target2 => (
        <div>
          <Descendant $as={Foo} $combinators={[target1, target2]} />
        </div>
      )}
    </HoverSource2>
  )}
</HoverSource1>;
```
**Concepts**
- The order of the array passed to `Descendant` determines the precedence of styling. As an implementation detail, we can iteratively increase the specificity of generated rules to make this happen.
- Descendent combinator styles always take precedence over "normal styles".

There's still a lot that needs to be ironed out, especially in terms of figuring out all the implementation details, but this is probably the first API that I've liked for this feature.

**Comment by aronallen** [comment]
How would this work for non react users?

**Comment by femesq** [comment]
I was thinking on a way of doing this, but couldn't set-up my prototype project (CRA) to work with my modified version (`yarn add /path/to/cloned-styletron/packages/styletron-xxx` - any tip on this I appreciate).
My test would try to implement [this codepen](https://codepen.io/femesq/pen/RYKNJE?editors=1100) in [this CRA app](https://github.com/femesq/styletron-descendant-test/blob/master/src/App.js) with the concept below:

```js
const Parent = styled("div", {
  display: 'flex',
  flexDirection: 'row',
  justifyContent: 'space-around',
  height: '50px',
  background: 'grey'
});

const Deep = styled("div", {
  padding: '20px',
  background: 'lightgrey'
});

const Child = styled("div", {
  alignSelf: 'center',
  height: '40px',
  width: '40px'
});

// suppose this generates ".aa" class
const DivA = withStyle(Child, {
  background: 'red'
});

// suppose this generates ".ab" class
const DivB = withStyle(Child, {
  background: 'green'
});
```

Then, we would have a `static` method on components created with `styled` or `withStyle`, so that we could make this:
```
/// method parameters:  Parent<Component>, cssSelector<string>, styles<object>
DivA.createDescendant(Parent, ':hover', { background: 'cyan' });
```

This call would append and `h_ba` class to Parent's classNames list, and the`ac` class to DivA classNames list, so that we can add the composite style like this:
```css
.h_ba:hover .ac {
  background: cyan;
}
```

Since it's a simple string concatenation, It would also work for `>` and `+` as selectors.

There could be more than one descendant. The browser would take care o rendering the more specific/strict css rule.

Maybe there is something I'm missing (sorry about that), but I hope I can still contribute to the discussion.

Thanks,

**Comment by femesq** [comment]
Have spent some time on this...

Although it was interesting to get deeper and know the code better, I got stuck so that I can't say this approach is possible..

If you guys could [take a look](https://github.com/femesq/styletron/commit/f904eb2b3cde1a343e78587a6e8a1ee9b3574360#diff-d42c22fd0d954d94a0e60f6fb6278aefR582) and comment it would be great...

Not sure if it's possible to 'reach' the `engine` outside the `<Consume>` component... If not, this approach may be inviable or the **magic** would must happen [here](https://github.com/femesq/styletron/commit/f904eb2b3cde1a343e78587a6e8a1ee9b3574360#diff-d42c22fd0d954d94a0e60f6fb6278aefR532), possibly previously creating random class-name to `Parent` (or, to avoid clashes, create a hash of `Parent+Child` displayName).

**Comment by rtsao** [comment]
I think unless it is hard requirement that these hierarchical hover-based styling works without JS, a JS solution is probably going to be simpler than alternatives.

For example, given a Button that should highlight when the parent Card is hovered:

### Hooks
```js
import {useHoverState} from "somewhere-else";

function SomeView() {
  const [targetProps, hoverState] = useHoverState();

  return (
    <Card {...targetProps} size="large">
      <h1>Hover me</h1>
      <Button highlighted={hoverState}>Click me</Button>
    </Card>
  );
}
```

### Render prop equivalent

```js
import {Hover} from "somewhere-else";

function SomeView() {
  return (
    <Hover>
      {({ targetProps, isHovered }) => (
        <Card {...targetProps} size="large">
          <h1>Hover me</h1>
          <Button highlighted={isHovered}>Click me</Button>
        </Card>
      )}
    </Hover>
  );
}
```

### Hoverable component
```js
import {Hoverable} from "somewhere-else";

function SomeView() {
  return (
    <Hoverable as={Card} size="large">
      {isHovered => (
        <>
          <h1>Hover me</h1>
          <Button highlighted={isHovered}>Click me</Button>
        </>
      )}
    </Hoverable>
  );
}

```

I think these generalized solutions pretty elegantly express the parent/child dependencies and is probably better than something specialized in Styletron, especially when it comes to customization of this sort of logic. JS is just more flexible.

**Comment by tajo** [comment]
https://www.styletron.org/concepts/#descendant-hover
