### ISSUE TITLE
Hydrate styles from CSS files

### ISSUE THREAD

**Issue by ianwalter** [styletron/styletron#268]
There are a couple feature requests (#179 and #193) for the ability to extract styles to a CSS file but I think I will be able to accomplish this via a Webpack loader. What I'm not sure how to do is hydrate the Styletron client from a CSS file instead of a `<style>` element.

**Comment by rtsao** [comment]
Hi Ian!

Regarding `styletron-engine-atomic` specifically, I think static css extraction may possibly lead to issues since the sequential, generated IDs are dependent on render order rather than the styles themselves.

That said, theoretically there could be a different styletron engine (https://github.com/styletron/styletron/issues/220) that *does* have class names determined fully by the styles themselves (in which case static extraction would be more possible).

Static extraction would indeed help with caching on subsequent pageloads, but involves some potential drawbacks including:
- Inlining critical CSS is probably better for initial pageloads
- Static css bundles may include unused or non-critical CSS

I think to achieve any practical benefit, any static extraction process would need to perform dead code elimination of JS (relating to the static styles), which is a quite a bit more involved. While theoretically possible, I think this is likely beyond the current scope of the project. Because one of the principles of Styletron is manipulation of styles via JS, I'm probably more inclined to defer to efforts such as https://github.com/facebook/prepack which attempt to solve this in a generic fashion.

Hope this helps!
