### ISSUE TITLE
Feature request: HostContent API for applying styles based on host-context of a styled component

### ISSUE THREAD

**Issue by matthewharwood** [styletron/styletron#272]
Sometimes it's useful to apply styles based on some condition outside of a component's view. For example, you need to apply a particular font size based on the lang attribute of the `<html lang="fi">`. 

Possible API:

```
const styledBlock = styled('p', () => {
  return {
   fontSize: '20px'
  }
});

const finnishStyledBlock = withHostContext('[lang="fi"] ', styledBlock, () => {
   return {
    fontSize: '10px',
   }
})
```
which would output:

```
[lang="fi"] .aa {
  ...
}
```

**Note:**
_This is a contrived example because I could use `p:lang(fi)` pseudo selector but there are many other examples e.g. body scroll locking, page to component theming, etc._

I know there are other possible approaches using react but it would be nice to have a simple css selector approach.

This api is borrowed from Angular's [host-context](https://angular.io/guide/component-styles#host-context ).

**Comment by tajo** [comment]
Thanks for the suggestion!

> I know there are other possible approaches using react but it would be nice to have a simple css selector approach.

I think this is the preferred approach when using CSS in JS. 

CSS selectors are a powerful thing and they can easily cross boundaries between unrelated components and create hidden dependencies. That doesn't scale all that well and it's also hard to test. So I'm closing this issue for now since we are not planning to support this.
