### ISSUE TITLE
Destructuring long form styles to short hand for atomic rendering.

### ISSUE THREAD

**Issue by illogikal** [styletron/styletron#280]
Styles `{"padding":"..."}` and `{"paddingTop":"..."}` in object yielding class "..." may result in unexpected behavior. Mixing shorthand and longhand properties within the same style object is unsupported with atomic rendering.

What would the performance impact of destructuring all long hand styles to short hand styles if there are both in the object.

What would the performance impact of always doing it be? Am curious if this was a design decision or just something that hasn't been considered yet. I would be willing to give it a go on implementing this but I am not familiar with Typescript. :(

**Comment by tajo** [comment]
Hey

> destructuring all long hand styles to short hand styles

Did you mean the opposite: short hands -> long hands?

If you wish that behavior, you might want to use this [library](https://www.npmjs.com/package/css-shorthand-properties) and implement your custom [styled](https://www.styletron.org/api/#createstyled) function.

However, I think this should be out of scope for this project since it might be perfectly valid to use and preserve shorthand properties.
