### ISSUE TITLE
yarn install fails when fetching csstype dependency from GitHub

### ISSUE THREAD

**Issue by tedwash** [styletron/styletron#347]
https://github.com/styletron/styletron/blob/c49949979079c60268379eaaea4309aa878b1ac7/packages/styletron-standard/package.json#L33

This dependency for the latest version of `styletron-react` is being resolved in my yarn.lock as version 2.6.4, a non-existent release of `csstype` (it seems to jump from 2.6.3 to 2.6.5). I believe it was introduced on the `styletron-standard` package bumped from 3.0.2 to [3.0.3](https://github.com/styletron/styletron/commit/53b4a2112d0482d826be8abfb81d65f8e45f79e8), which was then added to `styletron-react` in [5.2.4](https://github.com/styletron/styletron/commit/c49949979079c60268379eaaea4309aa878b1ac7)

"csstype@github:rtsao/csstype#c4e709f":
  version "2.6.4"
  resolved "https://codeload.github.com/rtsao/csstype/tar.gz/c4e709f5e047e9cacb721e437f53f0b84d6ada84"

I'm not super familiar with this notation for dependencies (I'm used to just stating the version). This might be an issue with an internal system, but when some developers build they get an error on yarn install, "An unexpected error occurred: “https://raw.githubusercontent.com/rtsao/csstype/c4e709f5e047e9cacb721e437f53f0b84d6ada84/package.json: unable to get local issuer certificate". It strikes me as odd since the dependency in `styletron-standard` v3.0.2 was [previously](https://github.com/styletron/styletron/commit/c49949979079c60268379eaaea4309aa878b1ac7) just 2.6.5.

I ended up rolling back to `styletron-react` 3.0.3 to avoid including the dependency, but was wondering anybody had insight about this.

**Comment by rtsao** [comment]
npm [supports installing dependencies from GitHub](https://docs.npmjs.com/files/package.json#github-urls) in a few ways, one of which is the following syntax: `<githubname>/<githubrepo>[#<commit-ish>]`.

The latest version of styletron-standard uses a fork of csstype to avoid a breaking change with regard to type definitions.

That particular install error seems rather strange (I actually haven’t seen that before), but what I could do is publish the fork to npm and use that instead of the GitHub dependency method.

**Comment by getdaydream** [comment]
when I try to install `styletron-react` 5.2.x, I get the below error :
![image](https://user-images.githubusercontent.com/23274794/68133937-48810580-ff5c-11e9-8444-d9082ebed987.png)
may be the same issue ?
