### ISSUE TITLE
Browser performance when parsing/rendering lots of classes?

### ISSUE THREAD

**Issue by codepunkt** [styletron/styletron#46]
Hello everyone!

Whats the browser performance of parsing/rendering lots of classes as opposed to a single class with lots of rules?

E.g. 10k elements with 15 classes each as opposed to 10k elements with 1 class and 15 rules each

Is this a factor in anything? :)

**Comment by rtsao** [comment]
A while back I used [cssstats.com](https://cssstats.com) to gather some metrics on CSS:

| Total Rules | Total Declarations | Mean Declarations Per Rule |              | 
|-------------|--------------------|----------------------------|--------------| 
| Airbnb      | 2732               | 6511                       | 2.383235725  | 
| Uber        | 2421               | 4435                       | 1.83188765   | 
| Twitter     | 6892               | 17200                      | 2.495647127  | 
| Pinterest   | 555                | 1007                       | 1.814414414  | 
| Kickstarter | 11500              | 24400                      | 2.12173913   | 
| Soundcloud  | 1042               | 2136                       | 2.049904031  | 
| Etsy        | 4126               | 9251                       | 2.242123122  | 
| Trulia      | 2609               | 5628                       | 2.157148333  | 
| Medium      | 3626               | 7765                       | 2.141478213  | 
| Craigslist  | 1180               | 2678                       | 2.269491525  | 
| GitHub      | 7584               | 17300                      | 2.281118143  | 
| YouTube     | 4531               | 11700                      | 2.582211432  | 
| Median      | 3179               | 7138                       | 2.199635727  | 
| STDEV       | 3197.292903        | 7206.097008                | 0.2332139619 | 

On average, there's 2 declarations per rule. This is actually remarkably consistent across all websites I tested (just 0.23 standard deviation!)

With atomic CSS, there's exactly one declaration per rule. So in practice, even if it were slower to have more classes (which I'm not sure either way) it wouldn't be a major impact, since essentially you simply double the number of classes, which is far from an order-of-magnitude increase.

I'd be interested in seeing benchmarks that could show something either way, though. But my guess is the time to parse class names in DOM elements is related to length of the class string rather than the number of classes. But I'm sure there's a ton of factors at play here, i.e. style calculation, etc.

**Comment by codepunkt** [comment]
@rtsao When considering a css-in-js solution, performance matters. Those statistics are really interesting! Nevertheless, i'm not sure that whatever i will build will have a mean declarations per rule thats in the ballpark shown.

**Comment by necolas** [comment]
[These tests](http://necolas.github.io/react-native-web/benchmarks/) surface the difference in layout timings (L) for different libs. The trees are very large, at the upper limit of the number of DOM nodes you can expect the browser to be optimized for. Layout takes a bit longer in chrome for libraries generating multiple classes, but it's not much

**Comment by rtsao** [comment]
I think we can mark this as resolved given results from the RNW benchmarks above. Thanks!
