### ISSUE TITLE
Mixing shorthand with longform

### ISSUE THREAD

**Issue by frenic** [styletron/styletron#68]
When you do something like this, `Baz` displays with `2rem` in padding due to the shorthand property in `Bar` even though it's changed with the longform property.

```js
const Foo = styled('div', {
  paddingLeft: '1rem', 
});

// <div class="a" />

const Bar = styled('div', {
  padding: '2rem', 
});

// <div class="b" />

const Baz = styled(Bar, {
  paddingLeft: '1rem', 
});

// <div class="b a" />
```

I noticed through #5 that the function `warnMixedProperties` exists, but I can't find that it's used anywhere.

What is best practice to handle this?

**Comment by rtsao** [comment]
Yeah, this is also a problem even with plain inline styles. To be un-opinionated and lightweight as possible I don't really do anything about this in the core.

I think a pretty good pattern is using helper functions that generate longform properties. I've built a collection of these for this purpose: https://lostyle.js.org/

This works nicely if you're using object spread syntax. For example if you're using the [`padding` helper](https://lostyle.js.org/global.html#padding):

```jsx
const Bar = styled('div', {
  ...padding('2rem'),
  ...padding({left: 1rem'})
});
```

I think ideally `warnMixedProperties` is added in `NODE_ENV=development` but I hadn't gotten around to integrating it yet. But it's there just in case other framework authors who may want to use it. Actually now I think about it, maybe it's a good idea to move it into a separate repo/package since it doesn't really have anything to do with Styletron specifically (just style object literals).

I have some ideas for solving this problem in a more robust, general way (somewhat unrelated to Styletron) but nothing concrete yet. Another problem I'm working on solving is robust Right-To-Left transformation at runtime.

**Comment by faddee** [comment]
I really like the idea of Strict Style Object Notation. However, it would be a small effort to wrap `warnMixedProperties` in `NODE_ENV=development` and something that would ease your workflow as developer, especially when debugging is hard.

That actually reminds me of asking: What is the best way of debugging? Sometime when you type a wrong value to a style property, it just renders as an empty CSS class. At least as shown in Chrome developer tools. And it's not that clear where CSS classes comes from when there's no source maps.

**Comment by vikfroberg** [comment]
An idea, could this be solved temporary by adding different specificity to rules.

For example
.a { border: 1px solid #fff; }
.b.b { border-bottom: none; }

Specificity is decided by number of dashes.

**Comment by vikfroberg** [comment]
What is the status of this? 

This has been a real problem for us in our project, we use "inline styles" see #72 which makes it more common for a developer to mix short and longhand properties.

It seems that when using `Iostyle` it will introduce a lot of additional styles, especially for properties like `border`.

If the goal of this project is to reduce the bytes rendered, do we really accomplish that? 

Additionally Styletron will create a class name for each of these properties which will in many cases increase the bytes compared to using a single class name like Aphrodite.

I'm not trying to bash on Styletron, I just want to provoke some thoughts.

**Comment by faddee** [comment]
With #91 you could add a plugin that parses all shorthand to longform before they injects.

**Comment by vikfroberg** [comment]
@faddee that will still introduce a lot of additional styles, just like `Iostyle`.

**Comment by pygy** [comment]
The same issue crops up for @media conditionals:

```JS

const Foo = styled('div', {
  color: 'red',
  '@media (min-width: 600px)' : {
    color: 'blue'
  }
});

const Bar = styled('div', {
  color: 'green', 
  '@media (min-width: 600px)' : {
    color: 'blue' // fetched from cache, `color: green` prevails since it is the latest definition.
  }
});

```

**Comment by rtsao** [comment]
`styletron-engine-atomic` provides development warnings for mixing shorthand/longform properties. Feel free to re-open if there's more issues. Thanks!
